export const data = {
  user1: {
    name: 'John Doe',
    profilePicture: 'https://i.ibb.co/Fq85sGjC/pngegg-2.png',
    photoUrl: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    username: 'johnte',
    description: 'Lorem ipsum dolor sit amet.',
  },
  user2: {
    name: 'Alan Smith',
    profilePicture: 'https://randomuser.me/api/portraits/men/32.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    username: 'alans',
    description: 'Lorem ipsum dolor sit amet.',
  },
  user3: {
    name: 'Emma Brown',
    profilePicture: 'https://randomuser.me/api/portraits/women/44.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    username: 'emmab',
    description: 'Consectetur adipiscing elit.',
  },
  user4: {
    name: 'Michael Johnson',
    profilePicture: 'https://randomuser.me/api/portraits/men/56.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
    username: 'mikej',
    description: 'Sed do eiusmod tempor incididunt.',
  },
  user5: {
    name: 'Sophia Davis',
    profilePicture: 'https://randomuser.me/api/portraits/women/68.jpg',
    photoUrl: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
    username: 'sophiad',
    description: 'Ut labore et dolore magna aliqua.',
  },
  user6: {
    name: 'James Wilson',
    profilePicture: 'https://randomuser.me/api/portraits/men/77.jpg',
    photoUrl: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    username: 'jamesw',
    description: 'Quis nostrud exercitation ullamco.',
  },
  user7: {
    name: 'Olivia Martinez',
    profilePicture: 'https://randomuser.me/api/portraits/women/81.jpg',
    photoUrl: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
    username: 'oliviam',
    description: 'Laboris nisi ut aliquip ex ea commodo.',
  },
  user8: {
    name: 'William Garcia',
    profilePicture: 'https://randomuser.me/api/portraits/men/89.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
    username: 'willg',
    description: 'Duis aute irure dolor in reprehenderit.',
  },
  user9: {
    name: 'Ava Lee',
    profilePicture: 'https://randomuser.me/api/portraits/women/90.jpg',
    photoUrl: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg',
    username: 'avalee',
    description: 'Voluptate velit esse cillum dolore.',
  },
  user10: {
    name: 'David Clark',
    profilePicture: 'https://randomuser.me/api/portraits/men/95.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_UL640_QL65_ML3_.jpg',
    username: 'davidc',
    description: 'Eu fugiat nulla pariatur.',
  },
};
